version: "3.5"

services:
  mongo:
    container_name: xta_mongo
    image: mongo:4.4
    networks:
      - xta
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: agenda
    ports:
      - "27017-27019:27017-27019"
    restart: unless-stopped

  redis:
    container_name: xta_redis
    image: redis:6
    networks:
      - xta
    ports:
      - "6379:6379"
    restart: unless-stopped

  xta-server:
    build: ./
    ports:
      - "3000:3000"
    networks:
      - xta
    environment:
      MONGODB_URL: mongodb://xta:password@mongo:27017/agenda
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

networks:
  xta:
    driver: bridge
